	SUBROUTINE READINI(NBUFLINE,MSGDEST)
c	USE MSFLIB
	USE DFLIB
	IMPLICIT NONE
	INTEGER MC
	PARAMETER (MC=80)
	INTEGER NBUFLINE,MSGDEST
	CHARACTER*9 FN/'CainW.ini'/
	CHARACTER*(MC) LINE
	INTEGER IFL,I,I1,I2,I3,I4,J,IOSTAT,IRTN
	REAL*8 X,FLOT1
	CHARACTER*260 NAM1,NAM2,EXT,CAINDIR
	INTEGER NCPATH,NCNAME,NCEXT
	CHARACTER(7) DEST(2)/'CONSOLE','FILE'/

c	open(15,file='temp.txt')
	CALL GETARG(0,NAM1)
	CALL SPLITPATH(NAM1,CAINDIR,NCPATH,NAM2,NCNAME,EXT,NCEXT)
	IFL=99
      NBUFLINE=0
	MSGDEST=0
	OPEN(IFL,FILE=CAINDIR(1:NCPATH)//FN,ACTION='READ',IOSTAT=IOSTAT,
     %      STATUS='OLD')
c				write(15,998) iostat
c998          format(' iostat=',I)
      IF(IOSTAT.NE.0) GOTO 320
100	READ(IFL,120,END=300) LINE
120   FORMAT(A)
      I1=0
	I3=-1
	
	DO 200 I=1,MC
	  IF(LINE(I:I).EQ.'=') THEN
	    IF(I1.EQ.0) GOTO 100
	    I3=0
	  ELSEIF(LINE(I:I).NE.' ') THEN
	    IF(I3.LT.0) THEN
	      IF(I1.EQ.0) I1=I
	      I2=I
	    ELSE
	      IF(I3.EQ.0) I3=I
	      I4=I
	    ENDIF
	  ENDIF
200   CONTINUE
	IF(I3.LE.0) GOTO 100
c	write(15,'(4A)') '*** ', LINE(I1:I2), '*** ',LINE(I3:I4)
	CALL TOUPPER(LINE(I1:I2))
	IF(LINE(I1:I2).EQ.'NBUFLINE') THEN
	  X=FLOT1(LINE(I+1:MC),MC-I,IRTN)
	  IF(IRTN.NE.0) GOTO 100
	  NBUFLINE=NINT(X)
	ELSEIF(LINE(I1:I2).EQ.'MSGDEST') THEN
	  CALL TOUPPER(LINE(I3:I4))
	  DO J=1,2
	    IF(LINE(I3:I4).EQ.DEST(J)) THEN
			  MSGDEST=J
	      EXIT
	    ENDIF
        ENDDO
	ENDIF
      GOTO 100
c	close(15)
300   CLOSE(IFL)
320	IF(NBUFLINE.EQ.0) NBUFLINE=200
	IF(NBUFLINE.LT.30) NBUFLINE=30
	IF(MSGDEST.EQ.0) MSGDEST=1
	OPEN(IFL,FILE=CAINDIR(1:NCPATH)//FN,ACTION='WRITE',IOSTAT=IOSTAT,
     %   STATUS='UNKNOWN')
	IF(IOSTAT.EQ.0) THEN
        WRITE(IFL,340) NBUFLINE
340     FORMAT('NBUFLINE=',I5)
        WRITE(IFL,360) DEST(MSGDEST)
360     FORMAT('MSGDEST=',A)
        CLOSE(IFL)
	ENDIF
      RETURN
	END