      SUBROUTINE BBFPSN(MX,MY,Q)
	USE BBPKCM
      IMPLICIT NONE
C      INCLUDE 'include/bbpkcm.h'
      INTEGER MX,MY
      REAL*8 Q(MX,MY,2)
      INTEGER I,J,L
      INTEGER NCALL/0/
C
      CALL CPUTIM('BBFPSN',1)
      NCALL=NCALL+1
      DO 200 J=1,NFY
*VOCL LOOP,NOVREC
      DO 200 I=1,NFX
        QF(I,J)=DCMPLX(0D0,0D0)
  200 CONTINUE
      DO 220 J=1,NXY(2)
*VOCL LOOP,NOVREC
      DO 220 I=1,NXY(1)
        QF(I,J)=DCMPLX(Q(I,J,1),Q(I,J,2))
 220  CONTINUE
      CALL ZFFT2(QF,2*MMX,NFX,NFY,-1,-1)
      DO 260 J=1,NFY
*VOCL LOOP,NOVREC
        DO 240 I=1,NFX
          PHIF(I,J)=QF(I,J)*KER(I,J)
 240    CONTINUE
 260  CONTINUE
      CALL ZFFT2(PHIF,2*MMX,NFX,NFY,1,1)
      DO 300 J=1,NXY(2)
*VOCL LOOP,NOVREC
      DO 300 I=1,NXY(1)
        PHI(I,J,1)=DREAL(PHIF(I,J))
        PHI(I,J,2)=DIMAG(PHIF(I,J))
 300  CONTINUE
C
      CALL BBDPHI
      DO 320 L=1,2
        LBBEXP(L)=0
 320  CONTINUE
C
      CALL CPUTIM('BBFPSN',2)
      RETURN
      END

