	SUBROUTINE BEAMALLOC(MP1,MVPH1,MPNEW1,IRTN)
	USE BEAMCM
	IMPLICIT NONE
	INCLUDE 'include/ctrlcm.h'
	INTEGER MP1,MVPH1,MPNEW1,IRTN
	INTEGER ISTAT

	IF(MP1.LE.1000) THEN
	  WRITE(MSGFL,200) MP1
200     FORMAT(' (SUBR.BEAMALLOC) MP=',I5,' too small.')
        IRTN=100
	  GOTO 990
	ENDIF
	IF(MVPH1.LE.1000) THEN
	  WRITE(MSGFL,220) MVPH1
220     FORMAT(' (SUBR.BEAMALLOC) MVPH=',I5,' too small.')
        IRTN=100
	  GOTO 990
	ENDIF
	IF(MPNEW1.LE.0) THEN
	  MPNEW1=INT(0.1D0*MP1)
	ENDIF
	MP=MP1
	MVPH=MVPH1
	MPNEW=MPNEW1
	ALLOCATE(KIND(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(GEN(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(LOST(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(ISBIN(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(IADRS(1:2,1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(LBBFIN(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(IWORK(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(WGT(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(TXYS(0:3,1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(EP(0:3,1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(SPIN(1:3,1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(FLD(1:3,1:2,1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(WORK(1:2*MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(PNAME(1:MP),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(IADRSV(1:MVPH),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(IDVPH(1:MVPH),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(EPVPH(0:3,1:MVPH),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(WGTVPH(1:MVPH),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	ALLOCATE(TXYVPH(0:3,1:MVPH),STAT=ISTAT)
	IF(ISTAT.NE.0) GOTO 900
	IRTN=0
	RETURN
900   IRTN=ISTAT
990   RETURN
      END

	SUBROUTINE BEAMDEALLOC
	USE BEAMCM
	IMPLICIT NONE
	INTEGER ISTAT

	DEALLOCATE(KIND,GEN,LOST,ISBIN,IADRS,LBBFIN,IWORK,STAT=ISTAT)
	DEALLOCATE(WGT,TXYS,EP,SPIN,FLD,WORK,STAT=ISTAT)
	DEALLOCATE(PNAME,STAT=ISTAT)
	DEALLOCATE(IADRSV,IDVPH,STAT=ISTAT)
	DEALLOCATE(EPVPH,WGTVPH,TXYVPH,STAT=ISTAT)

	RETURN
	END

