	SUBROUTINE BLALLOC(MMAG1,MBL1,IRTN)
	USE BEAMLN
	IMPLICIT NONE
	INTEGER MMAG1,MBL1,IRTN

	MMAG=MMAG1
	MBEAMLINE=MBL1
	NMAG=0
	NBEAMLINE=0
	NGSTRMG=0
	ALLOCATE(MAG(MMAG),STAT=IRTN)
	IF(IRTN.NE.0) RETURN
	ALLOCATE(BL(MBEAMLINE),STAT=IRTN)
	IF(IRTN.NE.0) THEN
	  DEALLOCATE(MAG,STAT=IRTN)
	  RETURN
	ENDIF
	IRTN=0
	RETURN
	END

	SUBROUTINE BLDEALLOC
	USE BEAMLN
	IMPLICIT NONE
	INTEGER ISTAT,I

	DEALLOCATE(MAG,STAT=ISTAT)
	IF(NBEAMLINE.GE.1) THEN
	  DO I=1,NBEAMLINE
	    CALL BLDEALLOC1(I)
	  ENDDO
	ENDIF
	DEALLOCATE(BL,STAT=ISTAT)
	RETURN
	END

	SUBROUTINE BLDEALLOC1(I)
	USE BEAMLN
	IMPLICIT NONE
	INTEGER I
	INTEGER ISTAT
	IF(I.GE.1.AND.I.LE.NBEAMLINE) THEN
	  DEALLOCATE(BL(I)%ELID,STAT=ISTAT)
	  DEALLOCATE(BL(I)%ELTYPE,STAT=ISTAT)
	  IF(BL(I)%NEXP.NE.0) THEN
	    DEALLOCATE(BL(I)%MAGID,STAT=ISTAT)
	    DEALLOCATE(BL(I)%MAGNID,STAT=ISTAT)
	    DEALLOCATE(BL(I)%SBL,STAT=ISTAT)
	    IF(BL(I)%LTWISS) THEN
	      DEALLOCATE(BL(I)%TWISS,BL(I)%TMAT,STAT=ISTAT)
	      BL(I)%LTWISS=.FALSE.
	    ENDIF
	    BL(I)%NEXP=0
	  ENDIF
	  BL(I)%NAME=' '
	  BL(I)%NEL=0
	ENDIF
	RETURN
	END