	SUBROUTINE CHECKNEST(NCMD,ICMD,CMDLN,LINE,IRTN)
	IMPLICIT NONE
	INTEGER NCMD,ICMD(NCMD),CMDLN(2,4,NCMD),IRTN
	CHARACTER(*) LINE(*)
	INCLUDE 'include/cmdnam.h'
	INCLUDE 'include/nestcm.h'
	INCLUDE 'include/ctrlcm.h'

	INTEGER IC,K,K1,IRP,II,I,I0
	LOGICAL FOUND
	CHARACTER(2*MNEST+3) BLANCK/' '/
	CHARACTER(50) TEXT
	INTEGER IC_CYCLE,IC_EXIT,IC_ELSEIF,IC_ELSE
	IC_CYCLE=2*MNEST_TYPE+1
	IC_EXIT=2*MNEST_TYPE+2
	IC_ELSEIF=2*MNEST_TYPE+3
	IC_ELSE=2*MNEST_TYPE+4

	IRP=0
100   IRP=IRP+1
C        repeat twice if error. print when IRP=2
	IF(IRP.EQ.2) WRITE(MSGFL,110)
110   FORMAT(' --- Nest Check of IF/DO/PUSH/TRANSPORT ---')
	II=0
	NESTLV=0
	INPUSH=0
	DO IC=1,NCMD
	  K=0
        DO K1=1,MNEST_TYPE
          IF(CMD(ICMD(IC)).EQ.LOPNAM(K1)) THEN
	      K=K1
	      EXIT
	    ELSEIF(CMD(ICMD(IC)).EQ.ENDNAM(K1)) THEN
	      K=K1+MNEST_TYPE
	      EXIT
	    ENDIF
	  ENDDO
	  IF(K.EQ.0) THEN
	    IF(CMD(ICMD(IC)).EQ.'CYCLE') THEN
	      K=IC_CYCLE
			ELSEIF(CMD(ICMD(IC)).EQ.'EXIT') THEN
	      K=IC_EXIT
	    ELSEIF(CMD(ICMD(IC)).EQ.'ELSEIF') THEN
	      K=IC_ELSEIF
	    ELSEIF(CMD(ICMD(IC)).EQ.'ELSE') THEN
	      K=IC_ELSE
	    ENDIF
	  ENDIF
	  IF(K.EQ.0) CYCLE
	  IF(IRP.EQ.2) THEN
	    I0=2*NESTLV
	    IF(K.LE.MNEST_TYPE) I0=I0+2
	    IF(CMDLN(1,2,IC).NE.0) THEN
	      IF(CMDLN(1,3,IC).NE.CMDLN(1,2,IC)) THEN
	        TEXT=LINE(CMDLN(1,2,IC))(CMDLN(2,2,IC):)
	      ELSE
	        TEXT=LINE(CMDLN(1,2,IC))(CMDLN(2,2,IC):CMDLN(2,3,IC))
	      ENDIF
	    ELSE
	      TEXT=' '
	    ENDIF
		  WRITE(MSGFL,'(A,1X,A)') 
     %       BLANCK(1:I0)//CMD(ICMD(IC))(1:NCCMD(ICMD(IC))),TEXT
	  ENDIF
	  IF(K.LE.MNEST_TYPE) THEN
          IF(NESTLV.EQ.MNEST) THEN
	      II=1
	      GOTO 320
	    ENDIF
          NESTLV=NESTLV+1
          NEST(NESTLV)=K
	    NESTST(NESTLV)=1
	    IF(CMD(ICMD(IC)).EQ.'PUSH'
     %            .OR.CMD(ICMD(IC)).EQ.'TRANSPORT') THEN
	      IF(INPUSH.NE.0) THEN
	        II=8
	        GOTO 320
	      ENDIF
            INPUSH=1
	    ENDIF
        ELSEIF(K.LE.2*MNEST_TYPE) THEN
	    K=K-MNEST_TYPE
	    IF(NESTLV.EQ.0) THEN
	      II=2
	      GOTO 320
	    ELSEIF(NEST(NESTLV).NE.K) THEN
	      II=2
	      GOTO 320
	    ENDIF
          NESTLV=NESTLV-1
	    IF(CMD(ICMD(IC)).EQ.'ENDPUSH'
     %      .OR.CMD(ICMD(IC)).EQ.'ENDTRANSPORT') INPUSH=0
	  ELSEIF(K.EQ.IC_CYCLE.OR.K.EQ.IC_EXIT) THEN
	    IF(NESTLV.EQ.0) THEN
	      II=3
	      GOTO 320
	    ENDIF
	    FOUND=.FALSE.
	    DO I=NESTLV,1,-1
	      IF(NEST(I).EQ.NEST_DO) THEN
	        FOUND=.TRUE.
	        EXIT
	      ELSEIF(NEST(I).EQ.NEST_PUSH.OR.NEST(I).EQ.NEST_TRANS) THEN
	        II=4
	        GOTO 320
	      ENDIF
	    ENDDO
	    IF(.NOT.FOUND) THEN
	      II=5
	      GOTO 320
	    ENDIF
	  ELSEIF(K.EQ.IC_ELSEIF) THEN
	    IF(NESTLV.EQ.0) THEN
	      II=3
	      GOTO 320
	    ELSEIF(NEST(NESTLV).NE.NEST_IF) THEN
	      II=6
	      GOTO 320
	    ELSEIF(NESTST(NESTLV).GE.3) THEN
		    II=7
	      GOTO 320
	    ENDIF
	    NESTST(NESTLV)=2
	  ELSEIF(K.EQ.IC_ELSE) THEN
	    IF(NESTLV.EQ.0) THEN
		    II=3
	      GOTO 320
	    ELSEIF(NEST(NESTLV).NE.NEST_IF) THEN
		    II=6
	      GOTO 320
	    ENDIF
	    NESTST(NESTLV)=3
	  ENDIF
      ENDDO
	IF(NESTLV.NE.0) II=9
 320  IF(II.NE.0) THEN
        IF(IRP.EQ.1) THEN
		  GOTO 100
	  ELSE
	    IRTN=1000+II
	    GOTO (900,905,910,915,920,925,930,935,940),II
	  ENDIF
	ENDIF
	IRTN=0
	GOTO 1000
900   WRITE(MSGFL,902) MNEST
902   FORMAT(' *** Nest level too deep. Exceeded',I3)
      GOTO 1000
905   WRITE(MSGFL,907) CMD(ICMD(IC))(1:NCCMD(ICMD(IC))),LOPNAM(K)
907   FORMAT(' *** ',A,' has no corresponding ',A)
	GOTO 1000
910   WRITE(MSGFL,912) CMD(ICMD(IC))(1:NCCMD(ICMD(IC)))
912   FORMAT(' *** Misplaced ',A)
      GOTO 1000
915   IF(NEST(I).EQ.NEST_PUSH) THEN
	  WRITE(MSGFL,917) CMD(ICMD(IC))(1:NCCMD(ICMD(IC))),'PUSH'
917     FORMAT(' *** Jump by breaks the ',A,' loop')
	ELSEIF(NEST(I).EQ.NEST_TRANS) THEN
	  WRITE(MSGFL,917) CMD(ICMD(IC))(1:NCCMD(ICMD(IC))),'TRANSPORT'
	ENDIF
      GOTO 1000
920   WRITE(MSGFL,922) CMD(ICMD(IC))(1:NCCMD(ICMD(IC)))
922   FORMAT(' *** No corresponding ENDIF found for ',A)
      GOTO 1000
925   WRITE(MSGFL,927) CMD(ICMD(IC))(1:NCCMD(ICMD(IC)))
927   FORMAT(' *** ',A,' not in IF nest.')
      GOTO 1000
930   WRITE(MSGFL,932)
932   FORMAT(' *** ELSEIF after ELSE.')
      GOTO 1000
935   WRITE(MSGFL,937)
937   FORMAT(' *** PUSH and TRANSPORT loops cannot nest.')
      GOTO 1000
940   WRITE(MSGFL,942)
942   FORMAT(' *** Following loop(s) not closed.')
      DO I=1,NESTLV
        WRITE(MSGFL,943) LOPNAM(NEST(I))
943     FORMAT(3X,A)
	ENDDO
1000  NESTLV=0
	INPUSH=0
	RETURN
	END
