      SUBROUTINE CLOCK1(T)
C  Cpu time in seconds from any origin which does not change
C  during a job.
      IMPLICIT NONE
      REAL*8 T,TSAVE
	INTEGER COUNT/0/,NRSET/0/,COUNT1,COUNTRATE,MAXCOUNT
	SAVE COUNT,NRSET

	CALL SYSTEM_CLOCK(COUNT1,COUNTRATE,MAXCOUNT)
	IF(COUNT1.LT.COUNT) NRSET=NRSET+1
	COUNT=COUNT1
	T=(DFLOAT(NRSET)*DFLOAT(MAXCOUNT)+DFLOAT(COUNT))/DFLOAT(COUNTRATE)

C  KEK version needs a C program second.c
c	REAL*8 SECOND
C
c      T=SECOND()
      RETURN
      END
