	SUBROUTINE DEFMAG(NAM,LENG,ANG,K1,ROT,APERT,EDGE,
     %     GSTRRD,NGSTRRD,IRTN)
	USE FLCHTYP
	USE BEAMLN
	IMPLICIT NONE
	INTEGER NGSTRRD,IRTN
	CHARACTER(*) NAM,GSTRRD
	TYPE(FLCHTYPE) LENG,K1
	REAL(8) ANG,ROT,APERT(2),EDGE(2)
      INCLUDE 'include/ctrlcm.h'
	INTEGER NC,I,II
	TYPE(FLCHTYPE) FC
	CHARACTER(80) ERR

	CALL CHKMAGNAME(NAM,NC)
	IF(NC.GT.MAXMAGNAME.OR.NC.LE.0) GOTO 900
	IF(LENG%L.EQ.2) THEN
	  CALL FLCHSET3(GSTRRD(LENG%C(1):LENG%C(2)),LENG,
     %    GSTRMG,NGSTRMG,ERR)
	  IF(ERR.NE.' ') GOTO 970
	  CALL EVAL0(GSTRMG(LENG%C(1):LENG%C(2)),FC,ERR)
	  IF(ERR.NE.' ') GOTO 950
	  IF(FC%L.NE.1) GOTO 960
	  LENG%X=FC%X
	ENDIF
	IF(K1%L.EQ.2) THEN
	  CALL FLCHSET3(GSTRRD(K1%C(1):K1%C(2)),K1,
     %    GSTRMG,NGSTRMG,ERR)
	  IF(ERR.NE.' ') GOTO 970
	  CALL EVAL0(GSTRMG(K1%C(1):K1%C(2)),FC,ERR)
	  IF(ERR.NE.' ') GOTO 950
	  IF(FC%L.NE.1) GOTO 960
	  K1%X=FC%X
	ENDIF
	IF(LENG%X.LT.0) GOTO 910
	IF(ANG.NE.0.AND.K1%X.NE.0) GOTO 920
	IF(NBEAMLINE.GE.1) THEN
	  DO I=1,NBEAMLINE
	    IF(NAM.EQ.BL(I)%NAME) GOTO 930
	  ENDDO
	ENDIF
	II=NMAG+1
	IF(NMAG.GE.1) THEN
	  DO I=1,NMAG
	    IF(NAM.EQ.MAG(I)%NAME) THEN
	      II=I
	      EXIT
	    ENDIF
	  ENDDO
	ENDIF
	IF(II.GT.NMAG) THEN
	  IF(NMAG.GE.MMAG) GOTO 940
	  NMAG=NMAG+1
	ELSE
	  IF(MSGLVL.GE.1) WRITE(MSGFL,180) NAM(1:NC)
180     FORMAT(' (SUBR.DEFMAG) Warning: Magnet "',A,'" redefined.')
	ENDIF
	MAG(II)%NAME=NAM
	MAG(II)%NC=NC
	MAG(II)%LENGTH=LENG
	MAG(II)%ANGLE=ANG
	MAG(II)%K1=K1
	MAG(II)%ROTATE=ROT
	DO I=1,2
	  MAG(II)%APERT(I)=APERT(I)
	  MAG(II)%TEDGE(I)=TAN(EDGE(I))
	ENDDO
	IRTN=0
	RETURN
900   IRTN=1000
	IF(MSGLVL.GE.0) WRITE(MSGFL,905) NAM
905   FORMAT(' (SUBR.DEFMAG) Invalid magnet name ','"',A,'"')
      GOTO 990
910	IRTN=1001
	IF(MSGLVL.GE.0) WRITE(MSGFL,915) NAM(1:NC)
915   FORMAT(' (SUBR.DEFMAG) negative magnet length ','"',A,'"')
	GOTO 990
920	IRTN=1002
	IF(MSGLVL.GE.0) WRITE(MSGFL,925) NAM(1:NC)
925   FORMAT(' (SUBR.DEFMAG) combined-function magnet not ready: ',
     %      '"',A,'"')
	GOTO 990
930	IRTN=1003
	IF(MSGLVL.GE.0) WRITE(MSGFL,935) NAM(1:NC)
935   FORMAT(' (SUBR.DEFMAG) Magnet name "','" already defined as ',
     %      'a beamline name.')
	GOTO 990
940	IRTN=1004
	IF(MSGLVL.GE.0) WRITE(MSGFL,945)
945   FORMAT(' (SUBR.DEFMAG) Too many magnets defined. ',/,
     %         '    Increase MMAG by ALLOCATE command.')
	GOTO 990
950   IRTN=1005
	IF(MSGLVL.GE.0) WRITE(MSGFL,955) ERR
955   FORMAT(' (SUBR.DEFMAG) Invalid expression.',/,3X,A)
      GOTO 990
960   IRTN=1006
	IF(MSGLVL.GE.0) WRITE(MSGFL,965)
965   FORMAT(' (SUBR.DEFMAG) Character type expression not accepted.')
      GOTO 990
970   IRTN=1007
	IF(MSGLVL.GE.0) WRITE(MSGFL,975)
975   FORMAT(' (SUBR.DEFMAG) Character buffer GSTRMG full.')
      GOTO 990
990   RETURN
	END
