	SUBROUTINE EVFIN
	USE FLCHTYP
	USE ARRAYMOD
	USE EVLMOD
      IMPLICIT NONE
C	INCLUDE 'include/evlmod.h'
	INTEGER I
	DO I=1,MLOAD
	  CALL EVLMFREE(I)
	ENDDO
	IF(NARRAY.GT.0) THEN
	  DO I=1,NARRAY
	    IF(ARR(I)%TYPE.NE.0) CALL EVARFREE(I)
	  ENDDO
	ENDIF
	RETURN
	END
