	SUBROUTINE EVLMFREE(IDLM)
	USE FLCHTYP
	USE EVLMOD
	IMPLICIT NONE
	INTEGER IDLM
C	INCLUDE 'include/evlmod.h'
	INTEGER ISTAT
	IF(IDLM.LE.0.OR.IDLM.GT.MLOAD) RETURN
	IF(LOADMOD(IDLM)%NP.GT.0) THEN
	  DEALLOCATE(LOADMOD(IDLM)%PL,STAT=ISTAT)
	  DEALLOCATE(LOADMOD(IDLM)%PC,STAT=ISTAT)
	  DEALLOCATE(LOADMOD(IDLM)%GSTRLM,STAT=ISTAT)
	  LOADMOD(IDLM)%NP=0
	ENDIF
	RETURN
	END

	SUBROUTINE EVARFREE(ID)
	USE ARRAYMOD
	IMPLICIT NONE
	INTEGER ID
	INTEGER ISTAT
	IF(ID.LE.0.OR.ID.GT.NARRAY) RETURN
	IF(ARR(ID)%TYPE.NE.0) THEN
	  IF(ARR(ID)%RANK.GE.1) DEALLOCATE(ARR(ID)%DIM,STAT=ISTAT)
	  IF(ARR(ID)%TYPE.EQ.1) THEN
	    DEALLOCATE(ARR(ID)%VAL,STAT=ISTAT)
	  ELSEIF(ARR(ID)%TYPE.EQ.2) THEN
	    DEALLOCATE(ARR(ID)%LC,STAT=ISTAT)
	  ENDIF
	  ARR(ID)%TYPE=0
	ENDIF
	IF(ID.EQ.NARRAY) NARRAY=NARRAY-1
	RETURN
	END
