	RECURSIVE SUBROUTINE FLCHSET2(TEXT,FC,ERR)
C  Set character string TEXT into GSTR2(EVALNEST)
	USE FLCHTYP
	USE ARRAYMOD
	IMPLICIT NONE
	TYPE(FLCHTYPE) FC
	CHARACTER(*) TEXT,ERR
	INTEGER NC

	NC=LEN(TEXT)
	IF(MGSTR2-NGSTR2(EVALNEST).LT.NC) THEN
	  ERR='Stack area GSTR2 full'
	  RETURN
	ENDIF
	FC%L=2
	FC%C(1)=NGSTR2(EVALNEST)+1
	NGSTR2(EVALNEST)=NGSTR2(EVALNEST)+NC
	FC%C(2)=NGSTR2(EVALNEST)
	IF(NC.GE.1) GSTR2(EVALNEST)(FC%C(1):FC%C(2))=TEXT(1:NC)
	ERR=' '
	RETURN
	END

	RECURSIVE SUBROUTINE FLCHSETN(TEXT,N,FC,ERR)
C  Set character string N*TEXT into GSTR2
	USE FLCHTYP
	USE ARRAYMOD
	IMPLICIT NONE
	TYPE(FLCHTYPE) FC
	INTEGER N
	CHARACTER(*) TEXT,ERR
	INTEGER NC,NC1,I

	NC1=LEN(TEXT)
	NC=NC1*N
	IF(MGSTR2-NGSTR2(EVALNEST).LT.NC) THEN
	  ERR='Stack area GSTR2 full'
	  RETURN
	ENDIF
	FC%L=2
	FC%C(1)=NGSTR2(EVALNEST)+1
	NGSTR2(EVALNEST)=NGSTR2(EVALNEST)+NC
	FC%C(2)=NGSTR2(EVALNEST)
	DO I=1,N
	  GSTR2(EVALNEST)(FC%C(1)+NC1*(I-1):FC%C(1)+NC1*I)=TEXT(1:NC1)
	ENDDO
	ERR=' '
	RETURN
	END

	RECURSIVE SUBROUTINE FLCHSET3(TEXT,FC,GSTR3,NGSTR3,ERR)
C  Set character string TEXT into GSTR3
	USE FLCHTYP
	IMPLICIT NONE
	TYPE(FLCHTYPE) FC
	CHARACTER(*) TEXT,GSTR3,ERR
	INTEGER NGSTR3
	INTEGER NC,MGSTR3

	MGSTR3=LEN(GSTR3)
	NC=LEN(TEXT)
	IF(MGSTR3-NGSTR3.LT.NC) THEN
	  ERR='Stack area GSTR3 full'
	  RETURN
	ENDIF
	FC%L=2
	FC%C(1)=NGSTR3+1
	NGSTR3=NGSTR3+NC
	FC%C(2)=NGSTR3
	GSTR3(FC%C(1):FC%C(2))=TEXT(1:NC)
	ERR=' '
	RETURN
	END