      FUNCTION IFRELI(LEFT,REL,RIGHT)
      INTEGER IFRELI,LEFT,REL,RIGHT
C
      IFRELI=0
      GOTO (11,12,13,14,15,16), REL
      RETURN
 11   IF(LEFT.EQ.RIGHT) IFRELI=1
      RETURN
 12   IF(LEFT.NE.RIGHT) IFRELI=1
      RETURN
 13   IF(LEFT.LT.RIGHT) IFRELI=1
      RETURN
 14   IF(LEFT.GT.RIGHT) IFRELI=1
      RETURN
 15   IF(LEFT.LE.RIGHT) IFRELI=1
      RETURN
 16   IF(LEFT.GE.RIGHT) IFRELI=1
      RETURN
      END
