      SUBROUTINE RDMAGNET(LN,LINE,NCHAR,IRTN)
	USE FLCHTYP
	USE READMOD
	USE BEAMLN
      IMPLICIT NONE
      INTEGER LN(2,3),NCHAR(*),IRTN
      CHARACTER*(*) LINE(*)
      INTEGER MOP
      PARAMETER (MOP=8)
      CHARACTER*13 OP(MOP)/'expression','LENGTH',
     %   'ANGLE','K1','ROTATE','APERTURE','EDGE','RECTANGULAR'/
      INTEGER NFF(MOP)/0,1,1,1,1,2,2,0/
      INTEGER IDLEN,IDANG,IDK1,IDROT,IDAPERT,IDEDGE
      INTEGER IOP(MOP)
      INCLUDE 'include/ctrlcm.h'
C      INCLUDE 'include/readcm.h'
      INTEGER J,I,NF,NC,NCNAM,K,LRECT
	TYPE(FLCHTYPE) SL,K1
	REAL(8) ANG,ROT,APERT(2),EDGE(2)
	CHARACTER(32) MAGNAM
C
      IRTN=0
      IF(LN(1,2).EQ.0) RETURN
      CALL CMDBLK('MAGNET',MOP,OP,0,NFF,MBL,NBL,KOP,KBL,REL,LNKW,LNBL,
     %    LN,LINE,NCHAR,IRTN)
      IF(IRTN.GT.1) GOTO 990
      IF(IRTN.EQ.1.OR.NBL.LE.0) RETURN
      DO 110 I=1,MOP
        IOP(I)=0
 110  CONTINUE
      J=1
      DO 180 I=1,MOP
        ID(I)=J
        IF(OP(I).EQ.'LENGTH') IDLEN=ID(I)
	  IF(OP(I).EQ.'ANGLE') IDANG=ID(I)
        IF(OP(I).EQ.'K1') IDK1=ID(I)
        IF(OP(I).EQ.'ROTATE') IDROT=ID(I)
	  IF(OP(I).EQ.'APERTURE') IDAPERT=ID(I)
	  IF(OP(I).EQ.'EDGE') IDEDGE=ID(I)
        J=J+MAX(0,NFF(I))
 180  CONTINUE
      DO 190 I=1,J-1
        PAR(I)=UNDEF
 190  CONTINUE
	NGSTRRD=0
	SL=ZERO
	ANG=0
	K1=ZERO
	ROT=0
	DO I=1,2
	  APERT(I)=0
	  EDGE(I)=0
	ENDDO
	LRECT=0
C
      DO 400 J=1,NBL
        I=KBL(J)
        IF(NFF(I).EQ.0) THEN
	    IOP(I)=1
          IF(OP(I).EQ.'expression') THEN
	      CALL BLKREC(LNKW(1,1,J),LINE,NCHAR,MAGNAM,NCNAM,IRTN,MSGFL)
	      IF(IRTN.NE.0) GOTO 990
CC	      IF(J.NE.1) GOTO 930
	      CALL APSOFF(MAGNAM(1:NCNAM),NCNAM)
	    ELSEIF(OP(I).EQ.'RECTANGULAR') THEN
	      LRECT=1
          ENDIF
        ELSEIF(NFF(I).GE.1) THEN
          CALL BLKREC(LNBL(1,1,J),LINE,NCHAR,TEXT,NC,IRTN,MSGFL)
          IF(IRTN.NE.0) GOTO 990
          DO 360 K=1,NFF(I)
	      FFF(K)=UNDEF
 360      CONTINUE
          CALL BLKRHS(TEXT(1:NC),FFF,MFFF,NF,GSTRRD,NGSTRRD,IRTN)
          IF(IRTN.NE.0) GOTO 990
          IF(NF.GT.NFF(I)) GOTO 910
          IF(NF.GE.1) THEN
            DO 380 K=1,NF
              IF(FFF(K).NE.UNDEF) THEN
                PAR(ID(I)+K-1)=FFF(K)
              ENDIF
 380        CONTINUE
          ENDIF
        ENDIF
 400  CONTINUE
	IF(IOP(1).EQ.0) GOTO 920
	IF(PAR(IDLEN).NE.UNDEF) SL=PAR(IDLEN)
	IF(PAR(IDK1).NE.UNDEF) K1=PAR(IDK1)
	IF(PAR(IDANG).NE.UNDEF) ANG=PAR(IDANG)%X
	IF(PAR(IDROT).NE.UNDEF) ROT=PAR(IDROT)%X
	DO I=1,2
	  IF(PAR(IDAPERT+I-1).NE.UNDEF) APERT(I)=PAR(IDAPERT+I-1)%X
	  IF(PAR(IDEDGE+I-1).NE.UNDEF) THEN
		  EDGE(I)=PAR(IDEDGE+I-1)%X
	  ELSEIF(LRECT.NE.0) THEN
	    EDGE(I)=ANG/2
	  ENDIF
	ENDDO
	CALL DEFMAG(MAGNAM(1:NCNAM),SL,ANG,K1,ROT,APERT,EDGE,
     %   GSTRRD,NGSTRRD,IRTN)
	IF(IRTN.NE.0) GOTO 990
C---
 800  IRTN=0
      RETURN
C---
C 900  IRTN=1000
C      WRITE(MSGFL,905) TEXT(1:NC)
C 905  FORMAT(' (SUBR.RDMAGNET) Invalid operand "',A,'".')
C      GOTO 1000
 910  IRTN=1001
      WRITE(MSGFL,915) OP(I)
 915  FORMAT(' (SUBR.RDMAGNET) Too many numbers for ',
     %  'operand "',A,'".')
      GOTO 1000
 920  IRTN=1002
      WRITE(MSGFL,925)
 925  FORMAT(' (SUBR.RDMAGNET) Magnet name not specified. ')
      GOTO 1000
 930  IRTN=1003
      WRITE(MSGFL,935) MAGNAM(1:NCNAM)
 935  FORMAT(' (SUBR.RDMAGNET) Invalid operand "',A,'". ',/,
     %    '   Must be the first operand if it is a magnet name.')
      GOTO 1000
 990  IRTN=1009
      GOTO 1000
 1000 RETURN
      END
