      SUBROUTINE RESTOLUM(UNIT,HEADER,IRTN)
	USE LUMCOM
      IMPLICIT NONE
      CHARACTER*(*) HEADER
      INTEGER UNIT,IRTN
      INCLUDE 'include/lumcom2.h'
      REAL*8 LUMR(-MWLUM+1:MWLUMR)
      INTEGER LUMI(MWLUMI)
      EQUIVALENCE (LUMR(-MWLUM+1),DLUM(1)),(LUMI(1),NLUM)
      INTEGER N,I
C
      READ(UNIT,'(A)',END=900) HEADER
      READ(UNIT,'(I10)',END=900) N
      IF(N.NE.0) THEN
        READ(UNIT,'(1P5D20.13)',END=900) (DLUM(I),I=1,N)
      ENDIF
      READ(UNIT,'(1P5D20.13)',END=900) (LUMR(I),I=1,MWLUMR)
      READ(UNIT,'(10I10)',END=900) (LUMI(I),I=1,MWLUMI)
      READ(UNIT,'(I10)',END=200) I
      GOTO 900
 200  IRTN=0
      RETURN
 900  IRTN=1000
      RETURN
      END

