	SUBROUTINE STOPCAIN(K)
C  Stop of execution must come here to release the allocated memory.
	IMPLICIT NONE
	INTEGER K,IRTN

	CALL CLOSEFILES
	CALL DISTDBG(0,0D0,0D0)

	CALL ALLOCMEM(2,IRTN)
	CALL FREELSRDT(0)
	CALL EVFIN

	IF(K.EQ.10) THEN
	  STOP 10
	ELSEIF(K.EQ.100) THEN
	  STOP 100
	ELSEIF(K.EQ.120) THEN
	  STOP 120
	ELSE
	  STOP
	ENDIF
	RETURN
	END
