	SUBROUTINE TOUPPER(A)
	IMPLICIT NONE
	CHARACTER*(*) A
	INTEGER N,I
	CHARACTER*1 CH
	INTEGER*1 K
	EQUIVALENCE (CH,K)
	CHARACTER*1 UA/'A'/,LA/'a'/
	INTEGER*1 IUA,ILA
	EQUIVALENCE (IUA,UA),(ILA,LA)
	N=LEN(A)
	IF(N.LE.0) RETURN
	DO 200 I=1,N
	  CH=A(I:I)
	  IF(CH.GE.'a'.AND.CH.LE.'z') THEN
	    K=K-ILA+IUA
	    A(I:I)=CH
	  ENDIF
200   CONTINUE
	RETURN
	END
