	MODULE BBPKCM
	  IMPLICIT NONE
	  INTEGER, PARAMETER:: MMOM=20
	  INTEGER MMX,MMY
	  INTEGER NXY(2),NFX,NFY,LBBEXP(2),NMOM,LEL,NCOULX,NCOULY
        REAL(8) DXY(2,2),XYMIN(2,2),XYMAX(2,2),XYCM(2,2),
     %      EL(2),R00(2),U00,EU0,CHU0,SHU0,ACOULX,ACOULY
	  COMPLEX(8) QMOM(0:MMOM,2,2)

	  REAL(8), ALLOCATABLE:: PHI(:,:,:),DPHI(:,:,:,:),
     %      COULF(:,:),QWORK(:)
	  COMPLEX(8), ALLOCATABLE:: KER(:,:),QF(:,:),PHIF(:,:)

C      INTEGER MMX,MMY,MMOM
C      PARAMETER (MMX=512,MMY=512,MMOM=20)
C      COMMON/BBPKCM/KER(2*MMX,2*MMY),QF(2*MMX,2*MMY),
C     %  PHIF(2*MMX,2*MMY),QWORK(8*MMX*MMY),QMOM(0:MMOM,2,2),
C     %  PHI(MMX,MMY,2),DPHI(3,MMX,MMY,2),COULF(2,(1+MMX)*(1+MMY)),
C     %  DXY(2,2),XYMIN(2,2),XYMAX(2,2),XYCM(2,2),
C     %  EL(2),R00(2),U00,EU0,CHU0,SHU0,ACOULX,ACOULY,
C     %  NXY(2),NFX,NFY,LBBEXP(2),NMOM,LEL,NCOULX,NCOULY
C      INTEGER NXY,NFX,NFY,LBBEXP,NMOM,LEL,NCOULX,NCOULY
C      REAL*8 PHI,DPHI,COULF,QWORK,DXY,XYMIN,XYMAX,XYCM,
C     %  EL,R00,U00,EU0,CHU0,SHU0,ACOULX,ACOULY
C      COMPLEX*16 KER,QF,PHIF,QMOM
C      COMPLEX*16 CWORK(4,MMX,MMY)
C      EQUIVALENCE (QWORK,CWORK)

      END MODULE BBPKCM
	  
