	MODULE EVLMOD
	  USE FLCHTYP
	  IMPLICIT NONE
        INTEGER, PARAMETER:: MGSTRLM=2048
	  TYPE LOADMODULE
	    INTEGER NP
	    INTEGER, POINTER:: PL(:,:)
	    TYPE(FLCHTYPE), POINTER:: PC(:)
	    INTEGER NGSTRLM
	    CHARACTER(MGSTRLM), POINTER:: GSTRLM
	  END TYPE LOADMODULE

	  INTEGER, PARAMETER:: MLOAD=5000
	  TYPE(LOADMODULE) LOADMOD(MLOAD)
	
	END MODULE EVLMOD
