	MODULE FLCHTYP
	  IMPLICIT NONE
        TYPE FLCHTYPE
c	    SEQUENCE
	    REAL(8) X
	    INTEGER C(2)
	    INTEGER L
c	    INTEGER IDUMMY
	  END TYPE FLCHTYPE
	  TYPE(FLCHTYPE) UNDEF,ZERO
	  INTERFACE OPERATOR(.EQ.)
	    MODULE PROCEDURE FLCHEQUAL
	  END INTERFACE
	  INTERFACE OPERATOR(.NE.)
	    MODULE PROCEDURE FLCHNOTEQUAL
	  END INTERFACE
	CONTAINS
	  FUNCTION FLCHEQUAL(A,B)
	    IMPLICIT NONE
	    TYPE(FLCHTYPE), INTENT(IN):: A,B
	    LOGICAL:: FLCHEQUAL
	    IF(A%L.EQ.B%L) THEN
	      IF(A%L.EQ.1) THEN
	        FLCHEQUAL=A%X.EQ.B%X
	      ELSE
	        FLCHEQUAL=(A%C(1).EQ.B%C(1)).AND.(A%C(2).EQ.B%C(2))
	      ENDIF
	    ELSE
	      FLCHEQUAL=.FALSE.
	    ENDIF
	  END FUNCTION FLCHEQUAL
	  FUNCTION FLCHNOTEQUAL(A,B)
	    IMPLICIT NONE
	    TYPE(FLCHTYPE), INTENT(IN):: A,B
	    LOGICAL:: FLCHNOTEQUAL
	    IF(A%L.EQ.B%L) THEN
	      IF(A%L.EQ.1) THEN
	        FLCHNOTEQUAL=A%X.NE.B%X
	      ELSE
	        FLCHNOTEQUAL=(A%C(1).NE.B%C(1)).OR.(A%C(2).NE.B%C(2))
	      ENDIF
	    ELSE
	      FLCHNOTEQUAL=.TRUE.
	    ENDIF
	  END FUNCTION FLCHNOTEQUAL
	END MODULE FLCHTYP