      MODULE LUMCOM
	IMPLICIT NONE
C         dimension for distribution map
	INTEGER MMM,MDD,MMDIM
C      PARAMETER (MMM=7,MDD=2**MMM,MMDIM=(4*MDD**2-1)/3)
	INTEGER NPKINL(3,2),MM
      REAL(8) XYMLUM(2,2),DXY(2),XYLMM(2,2),FREP,DTLUM,DSLUM,LUMFAC

	INTEGER,ALLOCATABLE:: NDD(:),NDD2(:),IPDD(:),KIJDD(:),IPBN(:,:,:)
      REAL(8),ALLOCATABLE:: DIST(:,:,:),VDIST(:,:,:)

C	INTEGER NDD(0:MMM),NDD2(0:MMM),IPDD(0:MMM),KIJDD(0:MDD-1),
C     %    IPBN(0:MDD**2-1,3,2),
C      REAL*8 DIST(0:MMDIM-1,3,2),VDIST(0:MMDIM-1,3,2)
C      COMMON/LUMCOM/DIST,VDIST,XYMLUM,DXY,XYLMM,FREP,DTLUM,DSLUM,
C     %   LUMFAC,NDD,NDD2,IPDD,KIJDD,NPKINL,IPBN,MM

      INTEGER MPPI
      PARAMETER (MPPI=4)
      CHARACTER*15 NAMPPI(MPPI)
C            NAMPPI defined in setcnst.f
      INTEGER LPPINT0,LPPINT(MPPI),LREPPI(MPPI),KVPH(2),KVPH0,
     %   LCLPPI,LFLPPI
      INTEGER,ALLOCATABLE:: IPBNV(:,:)
C	INTEGER IPBNV(0:MDD**2-1,2)
      REAL*8 ENHPPI(MPPI),EMNPPI
C      COMMON/PPICOM/ENHPPI,EMNPPI,LPPINT0,LPPINT,LREPPI,KVPH,KVPH0,
C     %   LCLPPI,LFLPPI,IPBNV
C      COMMON/PPICCOM/NAMPPI

	END MODULE LUMCOM
