      MODULE MATCHMOD
	  USE FLCHTYP
	  IMPLICIT NONE
	  INTEGER IDBLMATCH,NCBLNAM,LPER,NVAR,NCOND,NPOS,NCVARNAMMAX,
     %          NCCONDMAX
	  CHARACTER(16) BLNAM
	  REAL(8) CONV
        INTEGER, ALLOCATABLE:: KVAR(:,:),LVAR(:),NCVARNAM(:)
	  REAL(8), ALLOCATABLE:: XVAR(:),XVAR0(:)
	  CHARACTER(32), ALLOCATABLE:: VARNAM(:)
C          length includes the possible length for array index
	  TYPE(FLCHTYPE)  TWISSIN(8),MINFUN
	  TYPE(FLCHTYPE), ALLOCATABLE:: COND(:)
        INTEGER, PARAMETER:: MGSTRMATCH=10000
        INTEGER NGSTRMATCH
        CHARACTER(MGSTRMATCH)  GSTRMATCH
	END MODULE MATCHMOD