      INTEGER MPDFT,MVPHDFT,MMAGDFT,MBEAMLINEDFT,MBBXYDFT,MLUMMESHDFT
      PARAMETER (MPDFT=100000, MVPHDFT=10000, MMAGDFT=200, MBBXYDFT=128)
      PARAMETER (MBEAMLINEDFT=50, MLUMMESHDFT=128)
      INTEGER IALLOC,MP1,MVPH1,MPNEW1,MMAG1,MBEAMLINE1,MBBXY1,
     %   MLUMMESH1
      COMMON/ALLOCCM/IALLOC,MP1,MVPH1,MPNEW1,MMAG1,MBEAMLINE1,MBBXY1,
     %   MLUMMESH1
