      INTEGER MLEVEL
      PARAMETER (MLEVEL=10)
      INTEGER BLID(MLEVEL),ELN(MLEVEL),DIR(MLEVEL),LVL
	  REAL(8) APERT0(2,MLEVEL)
	  COMMON/BLEXPANDCOM/APERT0,BLID,ELN,DIR,LVL
C           DIR=-1 for reversed beamline
