      INTEGER LBMST,LCOHP,LPOLBS,LPOLCO,LENHBS,LENHCO,NCEHBS,NCEHCO,
     %     NPMXBS,NPMXCO
      REAL*8 PMAXBS,PMAXCO,WENHBS,WENHCO,PMMBS,PMMCO
      COMMON/CFQDCM/PMAXBS,PMAXCO,WENHBS,WENHCO,PMMBS,PMMCO,
     %  LBMST,LCOHP,LPOLBS,LPOLCO,LENHBS,LENHCO,NCEHBS,NCEHCO,
     %  NPMXBS,NPMXCO
      CHARACTER*256 ENHBS,ENHCO
      COMMON/CFQDCM2/ENHBS,ENHCO

