      INTEGER MIPAR
      PARAMETER (MIPAR=7)
      CHARACTER*16 IPARNM(MIPAR)/'MsgFile','OutFile',
     %  'OutFile2','TDFile','MsgLevel','Rand','Debug'/
      INTEGER IPAR0(MIPAR)/6,12,12,8,0,3,0/,IPAR(MIPAR)
      EQUIVALENCE (IPAR(1),MSGFL)
      INTEGER MRPAR
      PARAMETER (MRPAR=2)
      CHARACTER*16 RPARNM(MRPAR)/'Smesh','EqmErr'/
      REAL*8 RPAR0(MRPAR)/0D0,1D0/,RPAR(MRPAR)
C            see slveqm.f for EqmErr
      EQUIVALENCE (RPAR(1),SMESH),(RPAR(2),EQMERR)
      INTEGER MFLAG
      PARAMETER (MFLAG=2)
      INTEGER IFLAG0(MFLAG)/1,1/,IFLAG(MFLAG)
      EQUIVALENCE (IFLAG(1),ECHO)
      CHARACTER*8 FLAGNM(2+MFLAG)/'ON','OFF','ECHO','SPIN'/

