      INTEGER MCTTL0
      PARAMETER (MCTTL0=120)
      CHARACTER*8 VERSION
      CHARACTER*11 VERSIONDATE
      CHARACTER*20 JOBTIM
      CHARACTER*(MCTTL0) JOBTTL
      COMMON/HEADCM/JOBTIM,JOBTTL,VERSION,VERSIONDATE
