      INTEGER MMY,MMPH,MMXI,MMQ
      PARAMETER (MMY=200,MMPH=10,MMXI=200,MMQ=410)
      COMMON/NLBWCM/YY(0:MMY),XISQ(0:MMXI),QQ(MMQ),
     %   XISQMX,QMIN,QMAX,GALLMX(2),WGTBW(0:MMY),
     %   MY,MPH,MXI,MQ,NPHMIN,LN0(MMPH),NL0(MMQ)
      INTEGER MY,MPH,MXI,MQ,NPHMIN,LN0,NL0
      REAL*8 YY,XISQ,QQ,XISQMX,QMIN,QMAX,GALLMX,WGTBW
