 
      INTEGER MMY,MMPhi,MMPH,MMXI,MMLM
      PARAMETER (MMY=200,MMPhi=100,MMPH=10,MMXI=200,MMLM=200)
      COMMON/NLCPCM/YY(0:MMY),XISQ(0:MMXI),LM(0:MMLM),
     %   XISQMX,LMMAX,FALLMX(2),WGTCP(0:MMY),MY,Mphi,MPH,MXI,MLM
      INTEGER MY,Mphi,MPH,MXI,MLM
      REAL*8 YY,XISQ,LM,XISQMX,LMMAX,FALLMX,WGTCP
 