      INTEGER MMY,MMPH,MMXI,MMLM
      PARAMETER (MMY=100,MMPH=10,MMXI=100,MMLM=100)
      COMMON/NLCPCM/YY(0:MMY),XISQ(0:MMXI),LM(0:MMLM),
     %   XISQMX,LMMAX,FALLMX(2),WGTCP(0:MMY),MY,MPH,MXI,MLM
      INTEGER MY,MPH,MXI,MLM
      REAL*8 YY,XISQ,LM,XISQMX,LMMAX,FALLMX,WGTCP
