      INTEGER MTSTP
      PARAMETER (MTSTP=5000)
      INTEGER NTSTP,NTSTDT,IWTSTP(MTSTP),IWRNTS
      CHARACTER*4 TSTPNM(MTSTP),TSTPNM2(MTSTP)
      REAL*8 TSTPDT(11,MTSTP)
      COMMON/TSTPCM/TSTPDT,NTSTP,NTSTDT,IWTSTP,IWRNTS
      COMMON/TSTPCM2/TSTPNM,TSTPNM2
