      INTEGER MUFN00,MARG
      PARAMETER (MUFN00=1000,MARG=10)
      INTEGER NUFN,NVUFN(MUFN00)
      CHARACTER*(MCHAR) NAMUFN(MUFN00)
      CHARACTER*60 ERUFN
      COMMON/UFNCM/NVUFN,NUFN
      COMMON/UFNCM2/NAMUFN,ERUFN
